Hriday/add projects session
ubclaunchpad/LP-website pull request #343
Opened 2024-08-21 19:14 UTC by hriday330

- Created carousel component 
- integrated notion api for endpoint 
- cleaned up tailwind colours and mobile view

2024-08-21 22:57 UTC, armintalaie requested changes
Really good work but some suggestions on how to fetch the projects. 

(also not sure if u did but make sure you do `pnpm build` to make sure build passes - i will add that to the PR actions later)

2024-08-21 22:57 UTC, armintalaie commented on .anima/.gitignore
what is this directory for?

2024-08-21 22:57 UTC, armintalaie commented on src/app/lib/notion/projects.ts
> +  const notionApiKey = process.env.NOTION_DB_SECRET
can you add this env vars in the `.env.template`

2024-08-21 22:57 UTC, armintalaie commented on src/app/lib/notion/projects.ts
I like the function and how it's doing it but I wonder if intead of in memory we actually store it. So we can augment the build script by running this function and storing the result in somewhere like `lib/data/projects` so when we deploy it does that and we're good. 
We can additionally make an endpoint `/projects/refresh` that just calls this function and stores the data. 

in other words:
- Have the projects data to be first in somewhere as `projects.json` and it would be an empty array
- Make get projects persist to the file system and not in memory (store in the json)
- Have a route `api/portal/projects/refresh` that runs that function 

this helps us only do it when we want to revalidate our data but also it's behind the api so only us/execs can run it

2024-08-21 22:57 UTC, armintalaie commented on src/app/lib/notion/projects.ts
> +
let's add a tag on that page as "starred" and just get those and not based on year?

2024-08-21 22:57 UTC, armintalaie commented on src/components/general/projectSection.tsx
> +import { nunitoSans } from './../../app/fonts';
dont need to import this beyond the root layout

2024-08-22 20:12 UTC, hriday330 commented on .anima/.gitignore
oh looks like this was added by mistake

2024-08-23 01:06 UTC, armintalaie commented on src/app/lib/notion/projects.ts
> +  const notionApiKey = process.env.NOTION_DB_SECRET
@hriday330

2024-08-23 01:07 UTC, armintalaie approved these changes
Looks good. small issue with height should be fixed. hyperlink to the page and also adding the placeholder env vars to the .env.template. 
one ur done just run the `pnpm run format` and `pnpm run build` then push it and feel free to merge

2024-08-25 20:09 UTC, merged